### ISSUE TITLE
[BUG] Drug additional description will immediately close after it opens

### ISSUE THREAD

**Issue by dev-masih** [Mephiles/torntools_extension#293] opened 2020-11-29 18:18 UTC
i'm not sure about the exact reason but i think when there is a bit of slowness in the internet connection additional drug description is load when you select the drug but after a bit, the actual torn description will load and close the TT info area.
this might not be the real reason though.

![shaderTest](https://user-images.githubusercontent.com/8469800/100550073-97e35380-328c-11eb-8dfe-3b4aa52d440d.gif)

**Comment by DeKleineKobini** [comment] 2020-12-27 16:59
Duplicate of #205. Will add the gif to that too.

**Closed by DeKleineKobini** 2020-12-27 16:59 UTC
Labels: bug, duplicate
