### ISSUE TITLE
[BUG] Sidebar disappearing (edge case).

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#54] opened 2020-07-24 19:23 UTC
**Describe the bug**
The sidebar disappears during an edge case.

**To Reproduce**
1. Set icon order as other than default
2. Hide any icon through TornTools.
3. When any icon is dynamically changed on page by Torn then sidebar disappears (or disappears on reloading the page).

**Additional context**
Equal to bug 71 on Discord.

**Comment by raxty** [comment] 2020-10-05 07:13
Was this fixed already? I can't reproduce it

The only thing I noticed was screwed up margins when the icons updated dynamically, see #232 for that 😄

**Comment by DeKleineKobini** [comment] 2020-10-05 07:28
I'm not sure, I never experienced it myself (a lot of my issues on GitHub are mine because I transfer them from Discord to here regulary).

**Comment by DeKleineKobini** [comment] 2020-10-05 07:33
I'll leave it open for @Mephiles to check.

**Comment by Mephiles** [comment] 2020-10-05 07:43
I thought I fixed it by changing how the hidden icons are handled.

Before: Hidden icons were removed because the CSS created weird margins where some icons were closer than they should have been.

After: I moved hidden icons to the end of the list instead of removing them which a) removed the CSS issue and b) should have fixed the sidebar disappearing because icons are not deleted when Torn tries to search for them again

Didn't my patch fix the issue?

**Comment by raxty** [comment] 2020-10-05 08:13
I was asking since I didn't see any commit referencing this issue, so wasn't sure if this was already fixed.

Your patch did indeed fix it, but the CSS issue still appeared when the icons changed dynamically, but this got fixed with my patch, so I guess the issue can be closed now 😄

**Closed** 2020-10-05 08:30 UTC
Labels: bug
