### ISSUE TITLE
[BUG] FireFox force over DoctorN broken

### ISSUE THREAD

**Issue by tornapi** [Mephiles/torntools_extension#226] opened 2020-10-01 05:17 UTC
**Describe the bug**
When DoctorN and TornTools are installed at the same with the addon doesn't modify page contents when Force Over DoctorN is enabled.

**To Reproduce**
1. Install both.
2. Enable Force Torntools over DoctorN

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox 81

**Comment by tornapi** [comment] 2020-10-01 05:27
Actually this might just be that this extension doesn't work in FireFox.
Functionality keeps popping in and out.

**Comment by tornapi** [comment] 2020-10-01 05:34
Disabled DoctorN entirely, and still TornTools will not modify page contents. The toolbar icon popup and alerting works, but no other functionality works.

**Comment by DeKleineKobini** [comment] 2020-10-01 08:40
This was caused by issue #223, which was fixed in 5.1.2.

**Closed** 2020-10-01 08:39 UTC
Labels: bug
