### ISSUE TITLE
Standard Muted Notifications

### ISSUE THREAD

**Issue by Varides** [Mephiles/torntools_extension#447] opened 2021-03-25 13:47 UTC
Would it be possible to make the standard for notifications to be muted? Getting randomly wiped is fine, but when I check my phone at 3am and it starts *ding, ding, ding* the girlfriend gets a bit upset haha. 

Is it possible to just make the standard to have notifications muted by default and then people can enable them as they require? Its just really difficult trying to explain this to a non Torn playing girlfriend that it occurs randomly without my knowledge before hand. 

Otherwise, love the extension and everything you guys are doing with it. Keep up the great work!

**Comment by DeKleineKobini** [comment] 2021-03-25 13:58
Personally, I don't like the idea of them being disabled by default. I do understand it being incredibly annoying, but I don't see this as solution.

I'd recommend to setup your phone to be muted during nights. Not sure about iOS, but Android (9+) has timers enabled for 'do not disturb'. I use it myself to block notifications during the nights and it works perfectly.

**Comment by Varides** [comment] 2021-03-25 15:06
I mean, that was an example but the same issue occurs when I'm working. If it randomly resets during the work day, all of a sudden I start getting notifications of Torn events on my computer that can sometimes occur at inconvenient times (meetings, Phone calls, etc). I would think that the less intrusive option should be set as a default rather than the unmuted one. 

Since I use Chrome for both personal and work, I can't simply not have it occur at work if that is what it defaults to. Other applications/programs may include default sound on for their notifications, but when you change the settings in those applications (regardless of updates unless its bugged) it maintains your choices and remains muted. Its not even like I can just turn notifications off, as those will reset back to on as soon as I get logged out. 

To me, it just seems like a Quality of Life upgrade that should be defaulted as the alternative is obtrusive and doesn't provide a direct benefit. The benefit for those not having to turn notifications/sound on is less of a benefit than the detriment of those that need to have those notifications/sounds off. 

P.S. I don't want to turn notifications off for Torn either way, as they are useful to keep up to day to day, and I need the sounds on for my work related activities. Just some extra thoughts on the matter.

**Comment by Mephiles** [comment] 2021-03-26 07:29
I understand the issue is actually in TTs settings resetting. I don't think we'll turn the notifications off by default but v6 will most likely fix the resetting issue and thus improve your experience.

Although v6 will still take some time so I'm not sure what the best solution would be currently.

P.S. Just as extra info, I use Windows' built-in "focus mode" to disable all apps' notifications during meetings, etc.

**Comment by Varides** [comment] 2021-03-26 13:57
I'll attempt to find some solutions as suggested (both helpful) and wait for v6 to come out. Thank you for your responses!

**Comment by Mephiles** [comment] 2021-04-22 10:21
Closing this issue as notifications will be left ON by default, will try to improve the system onwards.

**Closed by Mephiles** 2021-04-22 10:21 UTC
Labels: suggestion
